---
- name: copy nginx repo config
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/

- name: copy epel repo config
  copy:
    src: epel.repo
    dest: /etc/yum.repos.d/

- name: copy remi repo config
  copy: 
    src: remi.repo
    dest: /etc/yum.repos.d/

- name: copy gpg key for nginx repo
  copy:
    src: RPM-GPG-KEY-NGINX
    dest: /etc/pki/rpm-gpg

- name: copy gpg key for epel repo
  copy: 
    src: RPM-GPG-KEY-EPEL-7
    dest: /etc/pki/rpm-gpg

- name: copy gpg key for remi repo
  copy: 
    src: RPM-GPG-KEY-remi
    dest: /etc/pki/rpm-gpg
