---
- name: stop and disable mariadb
  service:
    name: mariadb
    state: stopped
    enabled: no

- name: delete mariadb log file
  file:
    path: /var/log/mysqld.log
    state: absent

- name: delete mysql config file
  file:
    path: /etc/my.cnf
    state: absent

- name: uninstall mariadb and def packages
  yum: 
    name: "{{ item }}"
    state: absent
  with_items:
   - mariadb*
   - mysql*
   - MySQL-python
   - libselinux-python
