---
- name: install nginx package
  yum:
    name: nginx
    state: present

- name: copy nginx config
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: add firewalld rule
  firewalld:
    port: 80/tcp
#    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes

- name: restart nginx
  service: 
    name: nginx
    state: restarted
    enabled: yes
